name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'
        
    - name: Publish .NET Project
      run: dotnet publish GameScoreboard.csproj -c Release -o release --nologo
      
    # Change base tag in index.html from / to /GameScoreboard/
    - name: Change base tag
      run: sed -i 's/<base href="\/" \/>/<base href="\/GameScoreboard\/" \/>/' release/wwwroot/index.html
      
    # Add .nojekyll file to tell GitHub pages not to use Jekyll processing
    - name: Add .nojekyll file
      run: touch release/wwwroot/.nojekyll
      
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@4.1.3
      with:
        branch: gh-pages
        folder: release/wwwroot 